apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-ltsc2019
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iis-ltsc2019
  template:
    metadata:
      labels:
        app: iis-ltsc2019
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: iis-ltsc2019
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: iis-ltsc2019
---
apiVersion: v1
kind: Service
metadata:
  name: iis-ltsc2019-np
spec:
  ports:
  - port: 80
  selector:
    app: iis-ltsc2019
---
apiVersion: v1
kind: Service
metadata:
  name: iis-ltsc2019-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: iis-ltsc2019